/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAcceptanceRouteImport } from './routes/_authenticated/acceptance'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated/kitchen'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcceptanceRoute = AuthenticatedAcceptanceRouteImport.update({
  id: '/acceptance',
  path: '/acceptance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/acceptance': typeof AuthenticatedAcceptanceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/acceptance': typeof AuthenticatedAcceptanceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/acceptance': typeof AuthenticatedAcceptanceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/acceptance'
    | '/admin'
    | '/archive'
    | '/driver'
    | '/kitchen'
    | '/menu'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/acceptance'
    | '/admin'
    | '/archive'
    | '/driver'
    | '/kitchen'
    | '/menu'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/acceptance'
    | '/_authenticated/admin'
    | '/_authenticated/archive'
    | '/_authenticated/driver'
    | '/_authenticated/kitchen'
    | '/_authenticated/menu'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acceptance': {
      id: '/_authenticated/acceptance'
      path: '/acceptance'
      fullPath: '/acceptance'
      preLoaderRoute: typeof AuthenticatedAcceptanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAcceptanceRoute: typeof AuthenticatedAcceptanceRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcceptanceRoute: AuthenticatedAcceptanceRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
